routes/web.php
<?php

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::redirect('/', '/dashboard');

Route::prefix('/dashboard')->middleware(['auth'])->name('backend.')->group( function(){
    Route::get('/', 'Back\mainController@index')->name('index');
});

Route::prefix('/master/member')->middleware(['auth', 'role:admin'])->name('member.')->group( function(){
    Route::get('/', 'Back\memberController@index')->name('index');
    Route::get('/create', 'Back\memberController@create')->name('create');
    Route::post('/store', 'Back\memberController@store')->name('store');
    Route::get('/edit/{id}', 'Back\memberController@edit')->name('edit');
    Route::post('/update/{id}', 'Back\memberController@update')->name('update');
    Route::get('/destroy/{id}', 'Back\memberController@destroy')->name('destroy');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/back/mainController.php
<?php

namespace App\Http\Controllers\Back;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class mainController extends Controller
{
    public function index()
    {
        return view('back.home');
    }

    public function create()
    {
        //
    }
    
    public function store(Request $request)
    {
        //
    }
    
    public function show($id)
    {
        //
    }
    
    public function edit($id)
    {
        //
    }
    
    public function update(Request $request, $id)
    {
        //
    }
    
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/back/memberController.php
<?php

namespace App\Http\Controllers\Back;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;

class memberController extends Controller
{
    public function index()
    {
        $data['members'] = User::orderBy('role', 'ASC')->get(); 
        return view('back.member.index', $data);
    }

    public function create()
    {
        return view('back.member.create');
    }
    
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'email' => 'required|unique:users',
        ]);

        $user = new User;
        $user->name     = $request->name;
        $user->email    = $request->email;
        $user->role     = $request->role;
        $user->password = bcrypt($request->password);
        $user->save();

        return redirect()->route('member.index')->with('success', 'Member has been added successfully!');
    }
    
    public function edit($id)
    {
        $data['member'] = User::find($id);
        return view('back.member.edit', $data);
    }
    
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'email' => 'required|unique:users,email,'.$id,
        ]);

        $user = User::find($id);
        $user->name     = $request->name;
        $user->email    = $request->email;
        $user->role     = $request->role;
        if($request->password){
            $user->password = bcrypt($request->password);
        }
        $user->save();

        return redirect()->route('member.index')->with('success', 'Member has been updated successfully!');
    }
    
    public function destroy($id)
    {
        $user = User::find($id)->delete();
        return redirect()->route('member.index')->with('danger', 'Member has been deleted successfully!');
    }
}

resources/views/Layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/back/home.blade.php
@extends('back.master')
@section('content')
<div class="row clearfix">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <div class="row clearfix">
                    <div class="col-md-12">
                        <h2>About {{ config('app.name', 'AdminBSB - Boilerplate') }}</h2>
                    </div>
                </div>
            </div>
            <div class="body">
                <p>
                    {{ config('app.name', 'AdminBSB - Boilerplate') }} is a simple application builded with AdminBSB Boilerplate by {{ env('APP_CREATOR', 'CODEBREEDER') }}.
                </p>
            </div>
        </div>
    </div>
</div>

<div class="row clearfix">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h2>Recent Information</h2>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-hover table-striped table-bordered js-basic-example dataTable">
                        <thead>
                            <tr>
                                <th width="10%">Status</th>
                                <th>Message</th>
                                <th width="15%">Published</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><span class="label bg-red">important</span></td>
                                <td>This is your first message</td>
                                <td>{{date('M d, Y')}}</td>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/back/master.blade.php
@php
    $loguser = App\User::find(Auth::id());
@endphp
<!DOCTYPE html>
<html>
    <head>
        @include('back.partials.head')
    </head>
    <body class="theme-red">
        @include('back.partials.loader')
        @include('back.partials.navbar')
        <section>
            @include('back.partials.left-sidebar')
            @include('back.partials.right-sidebar')
        </section>
        <section class="content">
            <div class="container-fluid">
                @yield('content')
            </div>
        </section>
        @include('back.partials.script')
    </body>
</html>

resources/views/back/member/create.blade.php
@extends('back.master')
@section('content')
<div class="row clearfix">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <div class="row clearfix">
                    <div class="col-md-12">
                        <h2>Create Member</h2>
                    </div>
                </div>
            </div>
            <div class="body">
                <form action="{{route('member.store')}}" method="POST" autocomplete="off">
                    @csrf
                    <div class="row clearfix">
                        <div class="col-md-6 col-sm-12">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" name="name" class="form-control" value="{{ old('name') }}" required />
                                    <label class="form-label">Name</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <div class="form-group form-float">
                                <div class="">
                                    <select class="form-control show-tick" name="role" required>
                                        <option value="admin">Admin</option>
                                        <option value="member" selected>Member</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row clearfix">
                        <div class="col-md-6 col-sm-12">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="email" name="email" class="form-control" value="{{ old('email') }}" required />
                                    <label class="form-label">E-Mail</label>
                                </div>
                                @error('email')
                                <small style="color:red;">{{ $message }}</small>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="password" name="password" class="form-control" required />
                                    <label class="form-label">Password</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 text-right">
                            <input type="submit" value="Submit" class="btn btn-success btn-lg">
                            <input type="reset" value="Reset" class="btn btn-warning btn-lg">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<a type="button" class="btn btn-warning btn-circle-lg waves-effect waves-circle waves-float"
    style="position:fixed; bottom:20px; right:20px;" href="{{route('member.index')}}">
    <i class="material-icons">undo</i>
</a>
@endsection

resources/views/back/member/edit.blade.php
@extends('back.master')
@section('content')
<div class="row clearfix">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <div class="row clearfix">
                    <div class="col-md-12">
                        <h2>Edit Member</h2>
                    </div>
                </div>
            </div>
            <div class="body">
                <form action="{{route('member.update', $member->id)}}" method="POST" autocomplete="off">
                    @csrf
                    <div class="row clearfix">
                        <div class="col-md-6 col-sm-12">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" name="name" class="form-control" value="{{$member->name}}" required />
                                    <label class="form-label">Name</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <div class="form-group form-float">
                                <div class="">
                                    <select class="form-control show-tick" name="role" required>
                                        <option value="admin" {{($member->role=='admin')?'selected':''}}>Admin</option>
                                        <option value="member" {{($member->role=='member')?'selected':''}}>Member</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row clearfix">
                        <div class="col-md-6 col-sm-12">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="email" name="email" class="form-control" value="{{$member->email}}" required />
                                    <label class="form-label">E-Mail</label>
                                </div>
                                @error('email')
                                <small style="color:red;">{{ $message }}</small>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="password" name="password" class="form-control"/>
                                    <label class="form-label">Password [optional]</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 text-right">
                            <input type="submit" value="Submit" class="btn btn-success btn-lg">
                            <input type="reset" value="Reset" class="btn btn-warning btn-lg">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<a type="button" class="btn btn-warning btn-circle-lg waves-effect waves-circle waves-float"
    style="position:fixed; bottom:20px; right:20px;" href="{{route('member.index')}}">
    <i class="material-icons">undo</i>
</a>
@endsection

resources/views/back/member/index.blade.php
@extends('back.master')
@section('content')
@if(Session('success'))
    <div class="alert alert-alert-dismissible alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
        {{Session('success')}}
    </div>
@elseif(Session('danger'))
    <div class="alert alert-alert-dismissible alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
        {{Session('danger')}}
    </div>
@endif
<div class="row clearfix">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <div class="row clearfix">
                    <div class="col-md-12">
                        <h2>Member List</h2>
                    </div>
                </div>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-hover table-striped table-bordered js-basic-example dataTable">
                        <thead>
                            <tr>
                                <th width="5%">#</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th width="10%">Role</th>
                                <th width="15%">Registered</th>
                                <th width="10%">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($members as $n => $member)
                            <tr>
                                <td>{{$n+1}}</td>
                                <td>{{$member->name}}</td>
                                <td>{{$member->email}}</td>
                                <td>{{ucwords($member->role)}}</td>
                                <td>{{date('M d, Y', strtotime($member->created_at))}}</td>
                                <td class="text-center">
                                    <a class="btn btn-xs btn-warning waves-effect" href="{{route('member.edit', $member->id)}}">
                                        <i class="material-icons">settings</i>
                                    </a>
                                    @if($member->id != Auth::id())
                                    <a class="btn btn-xs btn-danger waves-effect"
                                        href="{{route('member.destroy', $member->id)}}"
                                        onclick="return confirm('Are you sure want to delete this member?');">
                                        <i class="material-icons">delete</i>
                                    </a>
                                    @endif
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<a type="button" class="btn btn-success btn-circle-lg waves-effect waves-circle waves-float"
    style="position:fixed; bottom:20px; right:20px;" href="{{route('member.create')}}">
    <i class="material-icons">add</i>
</a>
@endsection

resources/views/back/partials/head.blade.php
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<meta name="keywords" content="HTML,CSS,XML,JavaScript">
<meta name="author" content="{{ env('APP_CREATOR', 'CODEBREEDER') }}">
<title>{{ config('app.name', 'AdminBSB - Boilerplate') }}</title>
<link rel="icon" href="{{asset('vendor/AdminBSB')}}/favicon.ico" type="image/x-icon">
<link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
<link href="{{asset('vendor/AdminBSB')}}/plugins/bootstrap/css/bootstrap.css" rel="stylesheet">
<link href="{{asset('vendor/AdminBSB')}}/plugins/node-waves/waves.css" rel="stylesheet" />
<link href="{{asset('vendor/AdminBSB')}}/plugins/animate-css/animate.css" rel="stylesheet" />
<link href="{{asset('vendor/AdminBSB')}}/plugins/morrisjs/morris.css" rel="stylesheet" />
<link href="{{asset('vendor/AdminBSB')}}/css/style.css" rel="stylesheet">
<link href="{{asset('vendor/AdminBSB')}}/css/themes/all-themes.css" rel="stylesheet" />

<link href="{{asset('vendor/AdminBSB')}}/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
<link href="{{asset('vendor/AdminBSB')}}/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">
@yield('css')

resources/views/back/partials/left-sidebar.blade.php
<aside id="leftsidebar" class="sidebar">
    <div class="user-info">
        <div class="row">
            <a href="">
                <div class="image col-xs-2">
                    <img src="{{asset('vendor/AdminBSB')}}/images/user.png" width="48" height="48" alt="User" />
                </div>
            </a>
            <div class="info-container col-xs-7">
                <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <b>{{$loguser->name}}</b></div>
                <div class="email">{{$loguser->email}}</div>
            </div>
            <div class="info-container col-xs-2" style="top:20px;">
                <a href="{{ route('logout') }}" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();" style="color:white;" title="Keluar">
                    <i class="material-icons">exit_to_app</i>
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </div>
    </div>
    
    <div class="menu">
        <ul class="list">
            <li class="header">MAIN NAVIGATION</li>
            <li class="{{(Request::segment(1) == 'dashboard')?'active':''}}">
                <a href="{{route('backend.index')}}">
                    <i class="material-icons">home</i>
                    <span>Home</span>
                </a>
            </li>
            <li class="{{(Request::segment(1) == 'master')?'active':''}}">
                <a href="javascript:void(0);" class="menu-toggle">
                    <i class="material-icons">settings</i>
                    <span>Master Data</span>
                </a>
                <ul class="ml-menu">
                    <li>
                        <a href="{{route('member.index')}}">
                            <span>Members</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    
    <div class="legal">
        <div class="copyright">
            &copy; {{date('Y')}} <a href="javascript:void(0);">{{ config('app.name', 'AdminBSB - Boilerplate') }}</a>.
        </div>
        <div class="version">
            <b>Version: </b> {{ env('APP_VERSION', 'Developing') }}
        </div>
    </div>
</aside>

resources/views/back/partials/loader.blade.php
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="preloader">
            <div class="spinner-layer pl-red">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
        <p>Please wait...</p>
    </div>
</div>

resources/views/back/partials/navbar.blade.php
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="">{{ config('app.name', 'AdminBSB - Boilerplate') }}</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">

                <!-- <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
                        <i class="material-icons">notifications</i>
                        <span class="label-count">1</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">NOTIFICATIONS</li>
                        <li class="body">
                            <ul class="menu">
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-light-green">
                                            <i class="material-icons">person_add</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4>12 new members joined</h4>
                                            <p>
                                                <i class="material-icons">access_time</i> 14 mins ago
                                            </p>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li> -->

                <li class="pull-right"><a href="javascript:void(0);" class="js-right-sidebar" data-close="true"><i class="material-icons">more_vert</i></a></li>
            </ul>
        </div>
    </div>
</nav>

resources/views/back/partials/script.blade.php
<script src="{{asset('vendor/AdminBSB')}}/plugins/jquery/jquery.min.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/bootstrap/js/bootstrap.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/bootstrap-select/js/bootstrap-select.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/node-waves/waves.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/jquery-countto/jquery.countTo.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/raphael/raphael.min.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/morrisjs/morris.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/chartjs/Chart.bundle.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/flot-charts/jquery.flot.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/flot-charts/jquery.flot.resize.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/flot-charts/jquery.flot.pie.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/flot-charts/jquery.flot.categories.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/flot-charts/jquery.flot.time.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/jquery-sparkline/jquery.sparkline.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/js/admin.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/js/pages/index.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/js/demo.js"></script>

<script src="{{asset('vendor/AdminBSB')}}/plugins/jquery-datatable/jquery.dataTables.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
<script src="{{asset('vendor/AdminBSB')}}/js/pages/tables/jquery-datatable.js"></script>

<script src="https://cdn.ckeditor.com/4.12.1/full/ckeditor.js"></script>

<script>
    CKEDITOR.replace('ckeditor');
    $('.dataTable').DataTable();
</script>

@yield('script')